version: "3.9"

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 4000:3000

  postgres:
    container_name: postgres
    build:
      context: ./postgres
    ports:
      - 6543:5432

  mongodb:
    container_name: mongodb
    build: 
      context: ./mongodb
    ports:
      - "27017:27017"