version: "3.9"

services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
    ports:
      - 6543:5432

  mongodb:
    container_name: mongodb
    build: 
      context: ./mongodb
    ports:
      - "27017:27017"